---
- name: F5 Cloud Services - DNS Load Balancing playbook
  hosts: all 
  connection: local
  vars_files: "../setup.yml"  

  tasks:

    - name: Get all private IP addresses of the webservers in a single list
      run_once: true
      set_fact:
        address_ipEndpoint_2: "{{ private_ips|default([]) + [hostvars[item].public_ip_address] }}"
      with_items: "{{ groups['tag_Role_bigip'] }}"

    - name: Print the BIG-IP public address
      run_once: true
      debug:
        var: address_ipEndpoint_2
